url=jdbc:sqlserver://SHADOWLCODE;instanceName=SQLEXPRESS;databaseName=MiBaseDatos;encrypt=true;trustServerCertificate=true
username=sa
password=root
driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
classpath= ./driver/mssql-jdbc-13.4.0.jre8.jar

changeLogFile=example-changelog.xml