url=jdbc:mysql://host.docker.internal:3306/MiBaseDatos
username=root
password=root
driver=com.mysql.cj.jdbc.Driver
classpath=./driver/mysql-connector-j-9.6.0.jar

changeLogFile=changeset/changelog_main.xml


### variables de entorno.
parameter.nombre_usuario = Javier
parameter.correo_usuario = javier.lopez@test.com

liquibase.hub.mode=off
