url=jdbc:sqlserver://localhost:1433;instanceName=SQLEXPRESS;databaseName=MiBaseDatos;encrypt=true;trustServerCertificate=true
username=sa
password=root
driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
classpath= ./driver/mssql-jdbc-13.4.0.jre8.jar

changeLogFile=changeset/changeset_001.xml


### variables de entorno.
parameter.nombre_usuario = JavierSql
parameter.correo_usuario = javierSql.lopez@test.com
